name: Create Branch on New Issue
on:
  issues:
    types: [opened]

jobs:
  create_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Branch
        run: |
          issue_title=$(jq -r '.issue.title' $GITHUB_EVENT_PATH)
          branch_name=$(echo $issue_title | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
          git checkout -b $branch_name
          git push origin $branch_name
